# Numpy matrices

In [1]:
import numpy as np

In [3]:
np.random.randint(0, 10, (2, 4, 3))

array([[[7, 1, 5],
        [2, 2, 7],
        [9, 9, 8],
        [7, 4, 0]],

       [[5, 0, 9],
        [3, 3, 0],
        [3, 3, 5],
        [2, 9, 7]]])

# Operations on Matrix

### Addition
#### 1)Matrix & Matrix
*  two matrices can only be added if their shape is same

In [9]:
A=np.random.randint(1, 10, (3,4))
B=np.random.randint(1, 10, (3,4))

In [10]:
A

array([[4, 5, 2, 9],
       [5, 8, 4, 4],
       [4, 8, 5, 6]])

In [11]:
B

array([[1, 5, 2, 2],
       [4, 4, 2, 9],
       [8, 4, 8, 3]])

In [13]:
A+B

array([[ 5, 10,  4, 11],
       [ 9, 12,  6, 13],
       [12, 12, 13,  9]])

#### 2)Matrix & Scalar
*  A scalar can be added to a matrix after creating the same shaped array filled with the scalar value

In [7]:
A

array([[8, 4, 5, 3],
       [6, 8, 6, 9],
       [1, 8, 9, 7]])

In [8]:
A+5

array([[13,  9, 10,  8],
       [11, 13, 11, 14],
       [ 6, 13, 14, 12]])

### Subtraction

In [14]:
A-B

array([[ 3,  0,  0,  7],
       [ 1,  4,  2, -5],
       [-4,  4, -3,  3]])

In [15]:
A-5

array([[-1,  0, -3,  4],
       [ 0,  3, -1, -1],
       [-1,  3,  0,  1]])

### Multiplication
#### 1)Element wise multiplicaton

In [16]:
A*5

array([[20, 25, 10, 45],
       [25, 40, 20, 20],
       [20, 40, 25, 30]])

#### 2)Matrix Multiplication

In [33]:
A=np.random.randint(1, 10, (2,4))
B=np.random.randint(1, 10, (4,3))
C=np.random.randint(1, 10, (3,5))

In [34]:
A=np.matrix(A)
B=np.matrix(B)
C=np.matrix(C)

In [35]:
A

matrix([[4, 1, 8, 6],
        [2, 7, 8, 3]])

In [36]:
B

matrix([[9, 3, 6],
        [4, 9, 3],
        [6, 9, 6],
        [6, 8, 1]])

In [37]:
C

matrix([[3, 7, 5, 7, 4],
        [2, 6, 2, 2, 6],
        [2, 5, 5, 9, 4]])

In [26]:
A*B

matrix([[120,  99,  89],
        [102,  94,  88]])

In [28]:
np.matmul(A, B)

matrix([[120,  99,  89],
        [102,  94,  88]])

In [38]:
B*C

matrix([[ 45, 111,  81, 123,  78],
        [ 36,  97,  53,  73,  82],
        [ 48, 126,  78, 114, 102],
        [ 36,  95,  51,  67,  76]])

In [39]:
m1=A*B
m2=m1*C
m2

matrix([[ 816, 2119, 1307, 1879, 1666],
        [ 834, 2194, 1310, 1870, 1774]])

In [40]:
m1=B*C
m2=A*m1
m2

matrix([[ 816, 2119, 1307, 1879, 1666],
        [ 834, 2194, 1310, 1870, 1774]])

In [42]:
A

matrix([[4, 1, 8, 6],
        [2, 7, 8, 3]])

In [43]:
A.transpose()

matrix([[4, 2],
        [1, 7],
        [8, 8],
        [6, 3]])

In [46]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
X=np.random.randint(1, 10, (5,5))
C=np.matrix(X)

In [57]:
inverse=np.linalg.inv(X)

In [66]:
np.round(X*np.matrix(inverse))

matrix([[ 1.,  0., -0.,  0.,  0.],
        [-0.,  1.,  0.,  0., -0.],
        [-0.,  0.,  1.,  0., -0.],
        [-0.,  0., -0.,  1.,  0.],
        [-0., -0.,  0., -0.,  1.]])