# BroadCasting

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [4]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

In [5]:
b+a

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

In [16]:
c=np.array([[1],[2],[3],[4]])

In [15]:
b+c

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [19]:
d=np.array([[1,2,3],[4,5,6]])

In [20]:
b+d

ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 