In [1]:
import numpy as np

In [51]:
m=np.matrix(np.arange(1,10).reshape(3,3))

In [52]:
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [42]:
m2=m.getT()
m2[1,1]=100
m2

matrix([[  0,   5],
        [  1, 100],
        [  2,   7],
        [  3,   8],
        [  4,   9]])

In [43]:
m

matrix([[  0,   1,   2,   3,   4],
        [  5, 100,   7,   8,   9]])

In [48]:
m.diagonal()

matrix([[  0, 100]])

In [56]:
m1=np.matrix('1,2;3,4')
m2=np.matrix('9,4;5,6')
np.dot(m1,m2)

matrix([[19, 16],
        [47, 36]])

In [57]:
m1.dot(m2)

matrix([[19, 16],
        [47, 36]])