In [12]:
import numpy as np

In [29]:
#1
my_array = np.array([[[[1,3,4]]]])
np.array(my_array, ndmin=5)
my_array.ndim

4

In [21]:
#2
Array1 = np.array([[1, 2, 3], [4, 5, 6]])
Array2 = np.array([[2, 3],[3, 2]])
np.dot(Array1,Array2)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [7]:
#3
array = np.array([10,3,1,203,404,204,20,302,30,402,192])
array[::-1]

array([192, 402,  30, 302,  20, 204, 404, 203,   1,   3,  10])

In [6]:
#4
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b) 

array([[4, 1],
       [2, 2]])

In [5]:
#5
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a, b)[2,3,2,1,2,2]

499128

In [49]:
#7
np.random.seed(100)
ar1 = np.random.uniform(1,50, 20)
np.where(a < 10, 10, np.where(a > 30, 30, a))
ar1

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [44]:
6#
a = np.array([3, 7, 32], dtype = complex)
print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


In [34]:
array1 = np.array([10,3,1,203,404,204,20,302,30,402,192])
array2 = [1,2,3,4] 
np.insert(array1, 4, array2) 

array([ 10,   3,   1, 203,   1,   2,   3,   4, 404, 204,  20, 302,  30,
       402, 192])

In [39]:
#10
np.full((3,3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [51]:
#14
array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
array[:3,1]

array([2, 5, 8])

In [57]:
#15
Array1 = np.arange(20,2)
Array2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(Array1)
print(Array2)


[]
[ 1  2  3  4  5  6  7  8  9 10]


In [72]:
#17
A = np.array([4,12,29])
B = np.array([13,21,4])
print(A)
print(B)
np.cross(A,B)

[ 4 12 29]
[13 21  4]


array([-561,  361,  -72])

In [64]:
#19
array=np.array([[1, list([1, 2])], [2, list([[1], [2]])], [3, list([[1, 2], [3, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 4, 5])]], dtype=object)
print(array)
array
{1: [1,2], 2: [[1],[2]], 3: [[1,2], [3,4], [4,5]], 4: [1], 5: [1,2,3,4,5]}

[[1 list([1, 2])]
 [2 list([[1], [2]])]
 [3 list([[1, 2], [3, 4], [4, 5]])]
 [4 list([1])]
 [5 list([1, 2, 3, 4, 5])]]


{1: [1, 2],
 2: [[1], [2]],
 3: [[1, 2], [3, 4], [4, 5]],
 4: [1],
 5: [1, 2, 3, 4, 5]}