In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [8]:
c=np.add(a,b)
print(c)

[5 7 9]


In [10]:
x=np.arange(6).reshape(2,3)
y=np.arange(7,13).reshape(2,3)
print(x, "\n", y)

[[0 1 2]
 [3 4 5]] 
 [[ 7  8  9]
 [10 11 12]]


In [28]:
theta=np.array([0,30,45,60,90])
np.arctan(theta)

array([0.        , 1.53747533, 1.54857776, 1.5541312 , 1.55968567])