In [1]:
import numpy as np

In [2]:
np.array.flatten?

Object `np.array.flatten` not found.


In [3]:
arr=np.array([[1,2,3],[7,6,5]])

In [4]:
arr.flatten?

In [7]:
arr2=arr.flatten('F')
print(arr2)

[1 7 2 6 3 5]


In [12]:
np.reshape?

In [13]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Original Array is: ", arr)
print(id(arr))
print()

arr2=arr.reshape(2,3)
print("Array (2,3) is: ", arr2)
print(id(arr2))
print()

arr3=arr.reshape(3,2)
print("Array (3,2) is: ", arr3)
print(id(arr3))

print()
arr3[1,0]=999
print(arr3)
print(arr)

Original Array is:  [[1 2 3]
 [4 5 6]]
139989026209504

Array (2,3) is:  [[1 2 3]
 [4 5 6]]
139989026749056

Array (3,2) is:  [[1 2]
 [3 4]
 [5 6]]
139989026274640

[[  1   2]
 [999   4]
 [  5   6]]
[[  1   2 999]
 [  4   5   6]]
