# Universal Functions in Numpy (UFuncs)

## Array Arithmetic

In [4]:
import numpy as np

In [9]:
a=np.array([6,4,2])
b=np.array([5,3,2])

c=np.array([[1,2,3],[4,5,6]])
d=np.array([[5,2,9],[2,8,4]])

print("a= ", a, "\nb= ", b, "\nc= ", c, "\nd= ", d)

a=  [6 4 2] 
b=  [5 3 2] 
c=  [[1 2 3]
 [4 5 6]] 
d=  [[5 2 9]
 [2 8 4]]


### Addition- add()

In [13]:
np.add(a,b)

array([11,  7,  4])

In [7]:
a+b

array([11,  7,  4])

In [10]:
c+d

array([[ 6,  4, 12],
       [ 6, 13, 10]])

### Subtraction- subtract()

In [14]:
np.subtract(a,b)

array([1, 1, 0])

In [11]:
a-b

array([1, 1, 0])

In [12]:
c-d

array([[-4,  0, -6],
       [ 2, -3,  2]])

### Multiplication- multiply()

In [15]:
np.multiply(a,b)

array([30, 12,  4])

In [16]:
a*b

array([30, 12,  4])

In [17]:
c*d

array([[ 5,  4, 27],
       [ 8, 40, 24]])

### Division- divide()